name: Maven Publish

on:
  push:
    branches: [ "release" ]
  workflow_dispatch:
    inputs:
      confirmToPublish:
        description: "Confirm to publish the Maven Center Repository?"
        required: true
        type: choice
        default: No
        options:
          - Yes
          - No

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ inputs.confirmToPublish == 'Yes' }}

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Maven Publish
        uses: qcastel/github-actions-maven-release@master
        env:
          JAVA_HOME: /usr/lib/jvm/java-1.8-openjdk/
        with:
          git-release-bot-name: "release-bot"
          git-release-bot-email: "release-bot@microsphere.io"
          release-branch-name: "release"

          maven-args: "--batch-mode --update-snapshots -P release"
          maven-servers: ${{ secrets.MVN_REPO_SERVERS }}

          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

          gpg-enabled: true
          gpg-key-id: ${{ secrets.GPG_KEY_ID }}
          gpg-key: ${{ secrets.GPG_KEY }}